name: theme_tailor_annotation
description: >
  Annotations for the Theme Tailor code-generator.
  This package does nothing without Theme Tailor.
version: 2.1.0
repository: https://github.com/Iteo/theme_tailor
issue_tracker: https://github.com/Iteo/theme_tailor/issues
homepage: https://github.com/Iteo/theme_tailor
documentation: https://github.com/Iteo/theme_tailor/blob/main/packages/theme_tailor/README.md

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  collection: ^1.15.0
  json_annotation: ^4.6.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.2.0
  json_serializable: ^6.3.2
