name: theme_tailor_toolbox_example
description: A new Flutter project.

publish_to: "none"

version: 0.0.1

environment:
  sdk: ">=2.18.0 <4.0.0"
  flutter: ">=3.0.0"

dependencies:
  benchmark_harness: ^2.1.0
  flutter:
    sdk: flutter

  theme_tailor_annotation: ^2.0.2
  theme_tailor_toolbox:
    path: ../.

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  theme_tailor: ^1.0.3

dependency_overrides:
  theme_tailor_annotation:
    path: ../../theme_tailor_annotation

  theme_tailor:
    path: ../../theme_tailor

flutter:
  uses-material-design: true
